name: Daniel Chapin
favicon: null
layout_spectrum: 0.274716030806303
typography_spectrum: 0.9544108684640378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.029053557896986604
  lightness: 0.08337985351681709
  saturation: 0.24164045485667884
  rhythmicContrast: 0.7593846470117569
purpose: []
